add fancy ANSI terminal control sequences

diff --git a/pdcfw b/pdcfw
--- a/pdcfw
+++ b/pdcfw
@@ -21,7 +21,7 @@ fi
 if [ -x ${MAIN_FUNC} ]; then
     source ${MAIN_FUNC}
 else
-    echo "pdcfw: file ${MAIN_FUNC} not present or executable, aborting!" > /dev/stderr
+    echo "${prog}: file ${MAIN_FUNC} not present or executable, aborting!" > /dev/stderr
     exit -1
 fi
 
@@ -34,37 +34,42 @@ case "$1" in
 
     dry)
 	shift
-	printf "${prog}: executing dry run, resulting rule set:\n\n" > /dev/stderr
+	printf "${prog}: executing dry run, resulting rule set:\n# Generated by ${prog} version ${version} on $(date)\n" > /dev/stderr
 
 	# execute the whole program with a dummy cmd
 	cat <(commit=true fwcmd="echo" _main)
 
-	printf "\n${prog}: dry run complete - apply rule set by executing pdcfw apply!\n" > /dev/stderr
+	printf "# Rule set evaluation complete on $(date)\n${prog}: dry run complete - apply rule set by executing pdcfw apply!\n" > /dev/stderr
 	;;
 
     apply)
 	shift
-	printf "${prog}: saving in-memory firewall rule set to ${IPTABLES_RULES}...\n"
+	printf "${prog}: saving current in-memory firewall rule set to ${IPTABLES_RULES}..."
 	save
-	printf "${prog}: flushing in-memory firewall rule set...\n"
+	[ $? -eq 0 ] && success || failure
+	printf "${prog}: flushing current in-memory firewall rule set..."
 	flush
-	printf "${prog}: executing rule set build starting from ${mainfunc}...\n"
+	[ $? -eq 0 ] && success || failure
+	printf "${prog}: executing rule set build from ${MAIN_FUNC} and committing..."
 	${restore} <(commit=true fwcmd="echo" _main)
-	printf "${prog}: rule set commit complete - view results with pdcfw show running!\n" 
+	[ $? -eq 0 ] && success || failure
 	;;
 
     flush)
 	shift
 	printf "${prog}: flushing IPTables ruleset...\n"
 	${fwcmd} --flush
+	[ $? -eq 0 ] && success || failure
 	;;
 
     restore)
+	printf "${prog}: restoring IPTables ruleset from ${IPTABLES_RULES}..."
 	${restore} < ${IPTABLES_RULES}
+	[ $? -eq 0 ] && success || failure
 	;;
 	
     *)
-	echo "${prog}: usage ${prog} {show|dry|apply|...}"
+	echo "${prog}: usage ${prog} {show|dry|apply|flush|restore}"
 	exit 1
 	;;
 esac
